esphome:
  name: presence_laser_sensor
  platform: ESP32
  board: esp32dev
  includes:
    - PresenceLaserSensor.h
  platformio_options:
    board_build.f_cpu: 160000000L

wifi:
  power_save_mode: none
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password
    ap_timeout: 30s
  reboot_timeout: 0s

captive_portal:

ota:
  password: !secret ota_password

logger:

api:

# Here 55 and 82 addresses is addresses of two lasers
# 82 is default I2C address
# By default address is 164 (0xa4)
# but I2C uses only elder 7 bit, so it is 82
# 55 is address that was set by next command
# Serial1.begin(9600, SERIAL_8N1, 26, 25);
# Serial1.print("s7-111#");
# To find out address you can use I2C scanner

sensor:
  - platform: custom
    lambda: |-
      auto customSensor = new PresenceLaserSensor(55, 82);
      App.register_component(customSensor);
      return {customSensor};

    sensors:
      name: "Presence laser sensor"
